# Site settings
name: Rick Winfrey
email: rick.winfrey@gmail.com
title: "Rick Winfrey"
description: "Rick Winfrey"
url: "https://rickwinfrey.com"
baseurl: "/"

markdown: kramdown
permalink: /:categories/:title

# http://en.wikipedia.org/wiki/Words_per_minute#Reading_and_comprehension
words_per_minute: 180
headings: ["Writings", "Sandbox", "References", "About"]

# Sass settings
sass:
  style: :compressed

# code highlighting
highlighter: rouge

# Social / Open Graph defaults
default_image: "/assets/images/default_og.png"


exclude: ['vendor', 'jekyll-cache']
